extIf="vtnet0"

# drop packets instead of rejecting
set block-policy drop

# state must be on the same interface
set state-policy if-bound

# antispoof for forged ip
antispoof for $extIf

# skip rules on loopback / localhost
set skip on lo0

# block traffic thru extIf
block in on $extIf

# allow ssh (ipv4 only)
pass in quick on $extIf inet proto tcp from any to $extIf port ssh

# allow traffic out
pass out on $extIf from any to any keep state

# allow http, https
pass in quick on $extIf inet proto tcp from any to $extIf port 80 keep state
pass in quick on $extIf inet proto tcp from any to $extIf port 443 keep state
