# Generated by Django 5.2.16 on 2026-07-08 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_delete_resourcepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioshowcaseitem',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='portfolioshowcaseitemlink',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='portfolioshowcasesection',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='projectshowcaseitem',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='projectshowcaseitemlink',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='projectshowcasesection',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='resourceshowcaseitem',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='resourceshowcaseitemlink',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='resourceshowcasesection',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='serviceshowcaseitem',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='serviceshowcaseitemlink',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='serviceshowcasesection',
            options={'ordering': ['sort_order']},
        ),
    ]
